global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'aws_ec2_metrics'
    ec2_sd_configs:
      - region: us-east-1
        access_key: YOUR_AWS_ACCESS_KEY
        secret_key: YOUR_AWS_SECRET_KEY
    relabel_configs:
      - source_labels: [__meta_ec2_private_ip]
        target_label: address
        replacement: '$1:9100'

  - job_name: 'local_node'
    static_configs:
      - targets: ['localhost:9100']