global:
  scrape_interval: 15s

scrape_configs:
  # AWS EC2 Monitoring
  - job_name: 'aws_ec2_metrics'
    ec2_sd_configs:
      - region: us-east-1
    relabel_configs:
      - source_labels: [__meta_ec2_private_ip]
        target_label: address
        replacement: '${1}:9100'

  # GCP GCE Monitoring
  - job_name: 'gcp_gce_metrics'
    gce_sd_configs:
      - project: "your-gcp-project-id"
        zone: "us-central1-a" 
    relabel_configs:
      - source_labels: [__meta_gce_instance_private_ip]
        target_label: address
        replacement: '${1}:9100'

  # Local Node Monitoring
  - job_name: 'local_node'
    static_configs:
      - targets: ['localhost:9100']
