name: Multi-Cloud Terraform Validation

on: 
  push:
    paths:
      - 'infrastructure/**'
  pull_request:
    paths:
      - 'infrastructure/**'

jobs:
  validate:
    name: Terraform Format & Validate (${{ matrix.provider }})
    runs-on: ubuntu-latest

    strategy:  #DRY Code
      matrix:
        provider: [aws, gcp]

    defaults:
      run:
        working-directory: infrastructure/${{ matrix.provider }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: tfsec Security Scan
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          working-directory: infrastructure/${{ matrix.provider}}
