name: Multi-Cloud Terraform Pipeline

on:
  push:
    paths:
      - 'infrastructure/**'
  pull_request:
    paths:
      - 'infrastructure/**'

jobs:
  terraform:
    name: Terraform Validate and Plan
    runs-on: ubuntu-latest

    strategy:
      matrix:
        provider: [aws, gcp]

    defaults:
      run:
        working-directory: infrastructure/${{ matrix.provider }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan -input=false